server:
  port: 8001
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yejingtao/forblog
          search-paths: /config
          username: username
          password: password